BEGIN TRANSACTION;

CREATE TABLE users
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    email TEXT UNIQUE NOT NULL,
    entries BIGINT DEFAULT 0,
    age SMALLINT,
    pet VARCHAR(100),
    joined TIMESTAMP NOT NULL
);

COMMIT;